// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta2/discuss_service.proto

package com.google.ai.generativelanguage.v1beta2;

public interface ExampleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ai.generativelanguage.v1beta2.Example)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An example of an input `Message` from the user.
   * </pre>
   *
   * <code>.google.ai.generativelanguage.v1beta2.Message input = 1;</code>
   * @return Whether the input field is set.
   */
  boolean hasInput();
  /**
   * <pre>
   * An example of an input `Message` from the user.
   * </pre>
   *
   * <code>.google.ai.generativelanguage.v1beta2.Message input = 1;</code>
   * @return The input.
   */
  com.google.ai.generativelanguage.v1beta2.Message getInput();
  /**
   * <pre>
   * An example of an input `Message` from the user.
   * </pre>
   *
   * <code>.google.ai.generativelanguage.v1beta2.Message input = 1;</code>
   */
  com.google.ai.generativelanguage.v1beta2.MessageOrBuilder getInputOrBuilder();

  /**
   * <pre>
   * An example of what the model should output given the input.
   * </pre>
   *
   * <code>.google.ai.generativelanguage.v1beta2.Message output = 2;</code>
   * @return Whether the output field is set.
   */
  boolean hasOutput();
  /**
   * <pre>
   * An example of what the model should output given the input.
   * </pre>
   *
   * <code>.google.ai.generativelanguage.v1beta2.Message output = 2;</code>
   * @return The output.
   */
  com.google.ai.generativelanguage.v1beta2.Message getOutput();
  /**
   * <pre>
   * An example of what the model should output given the input.
   * </pre>
   *
   * <code>.google.ai.generativelanguage.v1beta2.Message output = 2;</code>
   */
  com.google.ai.generativelanguage.v1beta2.MessageOrBuilder getOutputOrBuilder();
}
