// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta2/discuss_service.proto

package com.google.ai.generativelanguage.v1beta2;

public interface GenerateMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ai.generativelanguage.v1beta2.GenerateMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Candidate response messages from the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.Message candidates = 1;</code>
   */
  java.util.List<com.google.ai.generativelanguage.v1beta2.Message> 
      getCandidatesList();
  /**
   * <pre>
   * Candidate response messages from the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.Message candidates = 1;</code>
   */
  com.google.ai.generativelanguage.v1beta2.Message getCandidates(int index);
  /**
   * <pre>
   * Candidate response messages from the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.Message candidates = 1;</code>
   */
  int getCandidatesCount();
  /**
   * <pre>
   * Candidate response messages from the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.Message candidates = 1;</code>
   */
  java.util.List<? extends com.google.ai.generativelanguage.v1beta2.MessageOrBuilder> 
      getCandidatesOrBuilderList();
  /**
   * <pre>
   * Candidate response messages from the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.Message candidates = 1;</code>
   */
  com.google.ai.generativelanguage.v1beta2.MessageOrBuilder getCandidatesOrBuilder(
      int index);

  /**
   * <pre>
   * The conversation history used by the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.Message messages = 2;</code>
   */
  java.util.List<com.google.ai.generativelanguage.v1beta2.Message> 
      getMessagesList();
  /**
   * <pre>
   * The conversation history used by the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.Message messages = 2;</code>
   */
  com.google.ai.generativelanguage.v1beta2.Message getMessages(int index);
  /**
   * <pre>
   * The conversation history used by the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.Message messages = 2;</code>
   */
  int getMessagesCount();
  /**
   * <pre>
   * The conversation history used by the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.Message messages = 2;</code>
   */
  java.util.List<? extends com.google.ai.generativelanguage.v1beta2.MessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <pre>
   * The conversation history used by the model.
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.Message messages = 2;</code>
   */
  com.google.ai.generativelanguage.v1beta2.MessageOrBuilder getMessagesOrBuilder(
      int index);

  /**
   * <pre>
   * A set of content filtering metadata for the prompt and response
   * text.
   * This indicates which `SafetyCategory`(s) blocked a
   * candidate from this response, the lowest `HarmProbability`
   * that triggered a block, and the HarmThreshold setting for that category.
   * This indicates the smallest change to the `SafetySettings` that would be
   * necessary to unblock at least 1 response.
   * The blocking is configured by the `SafetySettings` in the request (or the
   * default `SafetySettings` of the API).
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.ContentFilter filters = 3;</code>
   */
  java.util.List<com.google.ai.generativelanguage.v1beta2.ContentFilter> 
      getFiltersList();
  /**
   * <pre>
   * A set of content filtering metadata for the prompt and response
   * text.
   * This indicates which `SafetyCategory`(s) blocked a
   * candidate from this response, the lowest `HarmProbability`
   * that triggered a block, and the HarmThreshold setting for that category.
   * This indicates the smallest change to the `SafetySettings` that would be
   * necessary to unblock at least 1 response.
   * The blocking is configured by the `SafetySettings` in the request (or the
   * default `SafetySettings` of the API).
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.ContentFilter filters = 3;</code>
   */
  com.google.ai.generativelanguage.v1beta2.ContentFilter getFilters(int index);
  /**
   * <pre>
   * A set of content filtering metadata for the prompt and response
   * text.
   * This indicates which `SafetyCategory`(s) blocked a
   * candidate from this response, the lowest `HarmProbability`
   * that triggered a block, and the HarmThreshold setting for that category.
   * This indicates the smallest change to the `SafetySettings` that would be
   * necessary to unblock at least 1 response.
   * The blocking is configured by the `SafetySettings` in the request (or the
   * default `SafetySettings` of the API).
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.ContentFilter filters = 3;</code>
   */
  int getFiltersCount();
  /**
   * <pre>
   * A set of content filtering metadata for the prompt and response
   * text.
   * This indicates which `SafetyCategory`(s) blocked a
   * candidate from this response, the lowest `HarmProbability`
   * that triggered a block, and the HarmThreshold setting for that category.
   * This indicates the smallest change to the `SafetySettings` that would be
   * necessary to unblock at least 1 response.
   * The blocking is configured by the `SafetySettings` in the request (or the
   * default `SafetySettings` of the API).
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.ContentFilter filters = 3;</code>
   */
  java.util.List<? extends com.google.ai.generativelanguage.v1beta2.ContentFilterOrBuilder> 
      getFiltersOrBuilderList();
  /**
   * <pre>
   * A set of content filtering metadata for the prompt and response
   * text.
   * This indicates which `SafetyCategory`(s) blocked a
   * candidate from this response, the lowest `HarmProbability`
   * that triggered a block, and the HarmThreshold setting for that category.
   * This indicates the smallest change to the `SafetySettings` that would be
   * necessary to unblock at least 1 response.
   * The blocking is configured by the `SafetySettings` in the request (or the
   * default `SafetySettings` of the API).
   * </pre>
   *
   * <code>repeated .google.ai.generativelanguage.v1beta2.ContentFilter filters = 3;</code>
   */
  com.google.ai.generativelanguage.v1beta2.ContentFilterOrBuilder getFiltersOrBuilder(
      int index);
}
