// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta2/model_service.proto

package com.google.ai.generativelanguage.v1beta2;

public final class ModelServiceProto {
  private ModelServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_GetModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_GetModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_ListModelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_ListModelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_ListModelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_ListModelsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8google/ai/generativelanguage/v1beta2/m" +
      "odel_service.proto\022$google.ai.generative" +
      "language.v1beta2\0320google/ai/generativela" +
      "nguage/v1beta2/model.proto\032\034google/api/a" +
      "nnotations.proto\032\027google/api/client.prot" +
      "o\032\037google/api/field_behavior.proto\032\031goog" +
      "le/api/resource.proto\"P\n\017GetModelRequest" +
      "\022=\n\004name\030\001 \001(\tB/\340A\002\372A)\n\'generativelangua" +
      "ge.googleapis.com/Model\":\n\021ListModelsReq" +
      "uest\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_token\030\003 " +
      "\001(\t\"j\n\022ListModelsResponse\022;\n\006models\030\001 \003(" +
      "\0132+.google.ai.generativelanguage.v1beta2" +
      ".Model\022\027\n\017next_page_token\030\002 \001(\t2\200\003\n\014Mode" +
      "lService\022\227\001\n\010GetModel\0225.google.ai.genera" +
      "tivelanguage.v1beta2.GetModelRequest\032+.g" +
      "oogle.ai.generativelanguage.v1beta2.Mode" +
      "l\"\'\202\323\344\223\002\032\022\030/v1beta2/{name=models/*}\332A\004na" +
      "me\022\257\001\n\nListModels\0227.google.ai.generative" +
      "language.v1beta2.ListModelsRequest\0328.goo" +
      "gle.ai.generativelanguage.v1beta2.ListMo" +
      "delsResponse\".\202\323\344\223\002\021\022\017/v1beta2/models\332A\024" +
      "page_size,page_token\032$\312A!generativelangu" +
      "age.googleapis.comB\227\001\n(com.google.ai.gen" +
      "erativelanguage.v1beta2B\021ModelServicePro" +
      "toP\001ZVgoogle.golang.org/genproto/googlea" +
      "pis/ai/generativelanguage/v1beta2;genera" +
      "tivelanguageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.ai.generativelanguage.v1beta2.ModelProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
        });
    internal_static_google_ai_generativelanguage_v1beta2_GetModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ai_generativelanguage_v1beta2_GetModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_GetModelRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_ai_generativelanguage_v1beta2_ListModelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_ai_generativelanguage_v1beta2_ListModelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_ListModelsRequest_descriptor,
        new java.lang.String[] { "PageSize", "PageToken", });
    internal_static_google_ai_generativelanguage_v1beta2_ListModelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_ai_generativelanguage_v1beta2_ListModelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_ListModelsResponse_descriptor,
        new java.lang.String[] { "Models", "NextPageToken", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.ai.generativelanguage.v1beta2.ModelProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
