// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta2/safety.proto

package com.google.ai.generativelanguage.v1beta2;

public final class SafetyProto {
  private SafetyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_ContentFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_ContentFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_SafetyFeedback_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_SafetyFeedback_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_SafetyRating_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_SafetyRating_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_SafetySetting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_SafetySetting_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1google/ai/generativelanguage/v1beta2/s" +
      "afety.proto\022$google.ai.generativelanguag" +
      "e.v1beta2\032\037google/api/field_behavior.pro" +
      "to\"\314\001\n\rContentFilter\022Q\n\006reason\030\001 \001(\0162A.g" +
      "oogle.ai.generativelanguage.v1beta2.Cont" +
      "entFilter.BlockedReason\022\024\n\007message\030\002 \001(\t" +
      "H\000\210\001\001\"F\n\rBlockedReason\022\036\n\032BLOCKED_REASON" +
      "_UNSPECIFIED\020\000\022\n\n\006SAFETY\020\001\022\t\n\005OTHER\020\002B\n\n" +
      "\010_message\"\232\001\n\016SafetyFeedback\022B\n\006rating\030\001" +
      " \001(\01322.google.ai.generativelanguage.v1be" +
      "ta2.SafetyRating\022D\n\007setting\030\002 \001(\01323.goog" +
      "le.ai.generativelanguage.v1beta2.SafetyS" +
      "etting\"\233\002\n\014SafetyRating\022I\n\010category\030\003 \001(" +
      "\01622.google.ai.generativelanguage.v1beta2" +
      ".HarmCategoryB\003\340A\002\022\\\n\013probability\030\004 \001(\0162" +
      "B.google.ai.generativelanguage.v1beta2.S" +
      "afetyRating.HarmProbabilityB\003\340A\002\"b\n\017Harm" +
      "Probability\022 \n\034HARM_PROBABILITY_UNSPECIF" +
      "IED\020\000\022\016\n\nNEGLIGIBLE\020\001\022\007\n\003LOW\020\002\022\n\n\006MEDIUM" +
      "\020\003\022\010\n\004HIGH\020\004\"\321\002\n\rSafetySetting\022I\n\010catego" +
      "ry\030\003 \001(\01622.google.ai.generativelanguage." +
      "v1beta2.HarmCategoryB\003\340A\002\022^\n\tthreshold\030\004" +
      " \001(\0162F.google.ai.generativelanguage.v1be" +
      "ta2.SafetySetting.HarmBlockThresholdB\003\340A" +
      "\002\"\224\001\n\022HarmBlockThreshold\022$\n HARM_BLOCK_T" +
      "HRESHOLD_UNSPECIFIED\020\000\022\027\n\023BLOCK_LOW_AND_" +
      "ABOVE\020\001\022\032\n\026BLOCK_MEDIUM_AND_ABOVE\020\002\022\023\n\017B" +
      "LOCK_ONLY_HIGH\020\003\022\016\n\nBLOCK_NONE\020\004*\325\001\n\014Har" +
      "mCategory\022\035\n\031HARM_CATEGORY_UNSPECIFIED\020\000" +
      "\022\034\n\030HARM_CATEGORY_DEROGATORY\020\001\022\032\n\026HARM_C" +
      "ATEGORY_TOXICITY\020\002\022\032\n\026HARM_CATEGORY_VIOL" +
      "ENCE\020\003\022\030\n\024HARM_CATEGORY_SEXUAL\020\004\022\031\n\025HARM" +
      "_CATEGORY_MEDICAL\020\005\022\033\n\027HARM_CATEGORY_DAN" +
      "GEROUS\020\006B\221\001\n(com.google.ai.generativelan" +
      "guage.v1beta2B\013SafetyProtoP\001ZVgoogle.gol" +
      "ang.org/genproto/googleapis/ai/generativ" +
      "elanguage/v1beta2;generativelanguageb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
        });
    internal_static_google_ai_generativelanguage_v1beta2_ContentFilter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ai_generativelanguage_v1beta2_ContentFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_ContentFilter_descriptor,
        new java.lang.String[] { "Reason", "Message", "Message", });
    internal_static_google_ai_generativelanguage_v1beta2_SafetyFeedback_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_ai_generativelanguage_v1beta2_SafetyFeedback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_SafetyFeedback_descriptor,
        new java.lang.String[] { "Rating", "Setting", });
    internal_static_google_ai_generativelanguage_v1beta2_SafetyRating_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_ai_generativelanguage_v1beta2_SafetyRating_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_SafetyRating_descriptor,
        new java.lang.String[] { "Category", "Probability", });
    internal_static_google_ai_generativelanguage_v1beta2_SafetySetting_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_ai_generativelanguage_v1beta2_SafetySetting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_SafetySetting_descriptor,
        new java.lang.String[] { "Category", "Threshold", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
