// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ai/generativelanguage/v1beta2/text_service.proto

package com.google.ai.generativelanguage.v1beta2;

public final class TextServiceProto {
  private TextServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_GenerateTextRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_GenerateTextRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_GenerateTextResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_GenerateTextResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_TextPrompt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_TextPrompt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_TextCompletion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_TextCompletion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_EmbedTextRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_EmbedTextRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_EmbedTextResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_EmbedTextResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ai_generativelanguage_v1beta2_Embedding_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ai_generativelanguage_v1beta2_Embedding_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7google/ai/generativelanguage/v1beta2/t" +
      "ext_service.proto\022$google.ai.generativel" +
      "anguage.v1beta2\0323google/ai/generativelan" +
      "guage/v1beta2/citation.proto\0321google/ai/" +
      "generativelanguage/v1beta2/safety.proto\032" +
      "\034google/api/annotations.proto\032\027google/ap" +
      "i/client.proto\032\037google/api/field_behavio" +
      "r.proto\032\031google/api/resource.proto\"\320\003\n\023G" +
      "enerateTextRequest\022>\n\005model\030\001 \001(\tB/\340A\002\372A" +
      ")\n\'generativelanguage.googleapis.com/Mod" +
      "el\022E\n\006prompt\030\002 \001(\01320.google.ai.generativ" +
      "elanguage.v1beta2.TextPromptB\003\340A\002\022\030\n\013tem" +
      "perature\030\003 \001(\002H\000\210\001\001\022\034\n\017candidate_count\030\004" +
      " \001(\005H\001\210\001\001\022\036\n\021max_output_tokens\030\005 \001(\005H\002\210\001" +
      "\001\022\022\n\005top_p\030\006 \001(\002H\003\210\001\001\022\022\n\005top_k\030\007 \001(\005H\004\210\001" +
      "\001\022L\n\017safety_settings\030\010 \003(\01323.google.ai.g" +
      "enerativelanguage.v1beta2.SafetySetting\022" +
      "\026\n\016stop_sequences\030\t \003(\tB\016\n\014_temperatureB" +
      "\022\n\020_candidate_countB\024\n\022_max_output_token" +
      "sB\010\n\006_top_pB\010\n\006_top_k\"\365\001\n\024GenerateTextRe" +
      "sponse\022H\n\ncandidates\030\001 \003(\01324.google.ai.g" +
      "enerativelanguage.v1beta2.TextCompletion" +
      "\022D\n\007filters\030\003 \003(\01323.google.ai.generative" +
      "language.v1beta2.ContentFilter\022M\n\017safety" +
      "_feedback\030\004 \003(\01324.google.ai.generativela" +
      "nguage.v1beta2.SafetyFeedback\"\037\n\nTextPro" +
      "mpt\022\021\n\004text\030\001 \001(\tB\003\340A\002\"\344\001\n\016TextCompletio" +
      "n\022\023\n\006output\030\001 \001(\tB\003\340A\003\022J\n\016safety_ratings" +
      "\030\002 \003(\01322.google.ai.generativelanguage.v1" +
      "beta2.SafetyRating\022[\n\021citation_metadata\030" +
      "\003 \001(\01326.google.ai.generativelanguage.v1b" +
      "eta2.CitationMetadataB\003\340A\003H\000\210\001\001B\024\n\022_cita" +
      "tion_metadata\"e\n\020EmbedTextRequest\022>\n\005mod" +
      "el\030\001 \001(\tB/\340A\002\372A)\n\'generativelanguage.goo" +
      "gleapis.com/Model\022\021\n\004text\030\002 \001(\tB\003\340A\002\"o\n\021" +
      "EmbedTextResponse\022L\n\tembedding\030\001 \001(\0132/.g" +
      "oogle.ai.generativelanguage.v1beta2.Embe" +
      "ddingB\003\340A\003H\000\210\001\001B\014\n\n_embedding\"\032\n\tEmbeddi" +
      "ng\022\r\n\005value\030\001 \003(\0022\363\003\n\013TextService\022\201\002\n\014Ge" +
      "nerateText\0229.google.ai.generativelanguag" +
      "e.v1beta2.GenerateTextRequest\032:.google.a" +
      "i.generativelanguage.v1beta2.GenerateTex" +
      "tResponse\"z\202\323\344\223\002+\"&/v1beta2/{model=model" +
      "s/*}:generateText:\001*\332AFmodel,prompt,temp" +
      "erature,candidate_count,max_output_token" +
      "s,top_p,top_k\022\271\001\n\tEmbedText\0226.google.ai." +
      "generativelanguage.v1beta2.EmbedTextRequ" +
      "est\0327.google.ai.generativelanguage.v1bet" +
      "a2.EmbedTextResponse\";\202\323\344\223\002(\"#/v1beta2/{" +
      "model=models/*}:embedText:\001*\332A\nmodel,tex" +
      "t\032$\312A!generativelanguage.googleapis.comB" +
      "\226\001\n(com.google.ai.generativelanguage.v1b" +
      "eta2B\020TextServiceProtoP\001ZVgoogle.golang." +
      "org/genproto/googleapis/ai/generativelan" +
      "guage/v1beta2;generativelanguageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.ai.generativelanguage.v1beta2.CitationProto.getDescriptor(),
          com.google.ai.generativelanguage.v1beta2.SafetyProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
        });
    internal_static_google_ai_generativelanguage_v1beta2_GenerateTextRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ai_generativelanguage_v1beta2_GenerateTextRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_GenerateTextRequest_descriptor,
        new java.lang.String[] { "Model", "Prompt", "Temperature", "CandidateCount", "MaxOutputTokens", "TopP", "TopK", "SafetySettings", "StopSequences", "Temperature", "CandidateCount", "MaxOutputTokens", "TopP", "TopK", });
    internal_static_google_ai_generativelanguage_v1beta2_GenerateTextResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_ai_generativelanguage_v1beta2_GenerateTextResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_GenerateTextResponse_descriptor,
        new java.lang.String[] { "Candidates", "Filters", "SafetyFeedback", });
    internal_static_google_ai_generativelanguage_v1beta2_TextPrompt_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_ai_generativelanguage_v1beta2_TextPrompt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_TextPrompt_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_google_ai_generativelanguage_v1beta2_TextCompletion_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_ai_generativelanguage_v1beta2_TextCompletion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_TextCompletion_descriptor,
        new java.lang.String[] { "Output", "SafetyRatings", "CitationMetadata", "CitationMetadata", });
    internal_static_google_ai_generativelanguage_v1beta2_EmbedTextRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_ai_generativelanguage_v1beta2_EmbedTextRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_EmbedTextRequest_descriptor,
        new java.lang.String[] { "Model", "Text", });
    internal_static_google_ai_generativelanguage_v1beta2_EmbedTextResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_ai_generativelanguage_v1beta2_EmbedTextResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_EmbedTextResponse_descriptor,
        new java.lang.String[] { "Embedding", "Embedding", });
    internal_static_google_ai_generativelanguage_v1beta2_Embedding_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_ai_generativelanguage_v1beta2_Embedding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ai_generativelanguage_v1beta2_Embedding_descriptor,
        new java.lang.String[] { "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.ai.generativelanguage.v1beta2.CitationProto.getDescriptor();
    com.google.ai.generativelanguage.v1beta2.SafetyProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
